#!/usr/bin/env node
// Generate an Ed25519 keypair for JWT signing and print PEM bodies (single
// base64 line each) suitable for `wrangler secret put JWT_PRIVATE_KEY` /
// `JWT_PUBLIC_KEY` pastes.
//
// Usage:
//   node scripts/gen-keypair.mjs
//
// Also writes `./maxbridge-jwt.keys.local.json` (gitignored) so the same pair
// can be reused across deploys — DO NOT commit or share.

import { generateKeyPairSync } from 'node:crypto';
import { writeFileSync } from 'node:fs';

const { privateKey, publicKey } = generateKeyPairSync('ed25519');
const priv = privateKey.export({ type: 'pkcs8', format: 'pem' }).toString();
const pub = publicKey.export({ type: 'spki', format: 'pem' }).toString();

const privBody = priv.replace(/-----BEGIN PRIVATE KEY-----/, '').replace(/-----END PRIVATE KEY-----/, '').replace(/\s+/g, '');
const pubBody = pub.replace(/-----BEGIN PUBLIC KEY-----/, '').replace(/-----END PUBLIC KEY-----/, '').replace(/\s+/g, '');

writeFileSync('./maxbridge-jwt.keys.local.json', JSON.stringify({
  note: 'Generated by gen-keypair.mjs — DO NOT commit. Paste `private` into `wrangler secret put JWT_PRIVATE_KEY`, `public` into `JWT_PUBLIC_KEY`.',
  privatePem: priv.trim(),
  publicPem: pub.trim(),
  privateBase64: privBody,
  publicBase64: pubBody,
  generatedAt: new Date().toISOString(),
}, null, 2));

console.log('\n# PASTE PRIVATE (JWT_PRIVATE_KEY):');
console.log(priv.trim());
console.log('\n# PASTE PUBLIC (JWT_PUBLIC_KEY):');
console.log(pub.trim());
console.log('\n# Also saved to ./maxbridge-jwt.keys.local.json (gitignored).');
